dist: bionic
language: node_js
node_js:
  - "8"
  - "10"
install:
  - npm install -g node-gyp
  - npm install -g node-pre-gyp
  - npm install
script:
  - npm run test:node
cache:
  directories:
    - "node_modules"
